import type { ProjectConfig, FolderNode } from "./types"

export function generateBashScript(config: ProjectConfig, folders: FolderNode[]): string {
  const lines: string[] = []

  lines.push("#!/bin/bash")
  lines.push("")
  lines.push("# ========================================")
  lines.push(`# Project: ${config.projectName}`)
  lines.push("# Generated by Devs Recipe")
  lines.push("# ========================================")
  lines.push("")

  // Create project directory
  lines.push(`echo "🚀 Creating project: ${config.projectName}"`)
  lines.push(`mkdir -p ${config.projectName}`)
  lines.push(`cd ${config.projectName}`)
  lines.push("")

  // Frontend setup
  if (config.frontend !== "none") {
    lines.push("# ========================================")
    lines.push("# Frontend Setup")
    lines.push("# ========================================")
    lines.push('echo "📦 Setting up frontend..."')
    lines.push("")

    const isTs = config.variant === "ts"

    switch (config.frontend) {
      case "react":
        lines.push(`npx create-vite@latest client --template react${isTs ? "-ts" : ""}`)
        break
      case "next":
        lines.push(
          `npx create-next-app@latest client ${isTs ? "--typescript" : "--js"} --tailwind --eslint --app --src-dir --import-alias "@/*"`,
        )
        break
      case "vue":
        lines.push(`npm create vue@latest client -- ${isTs ? "--typescript" : ""}`)
        break
      case "nuxt":
        lines.push(`npx nuxi@latest init client`)
        break
      case "svelte":
        lines.push(`npm create vite@latest client -- --template svelte${isTs ? "-ts" : ""}`)
        break
      case "sveltekit":
        lines.push(`npm create svelte@latest client`)
        break
      case "angular":
        lines.push(`npx @angular/cli new client ${isTs ? "" : "--skip-tests"}`)
        break
      case "solid":
        lines.push(`npx degit solidjs/templates/${isTs ? "ts" : "js"} client`)
        break
      case "qwik":
        lines.push(`npm create qwik@latest client`)
        break
      case "astro":
        lines.push(`npm create astro@latest client`)
        break
      case "remix":
        lines.push(`npx create-remix@latest client`)
        break
    }

    lines.push("cd client")
    lines.push("npm install")
    lines.push("")

    // Styling
    if (config.styling.includes("tailwind") && !["next", "nuxt"].includes(config.frontend)) {
      lines.push('echo "🎨 Installing Tailwind CSS..."')
      lines.push("npm install -D tailwindcss postcss autoprefixer")
      lines.push("npx tailwindcss init -p")
      lines.push("")
    }

    if (config.styling.includes("sass")) {
      lines.push('echo "🎨 Installing Sass..."')
      lines.push("npm install -D sass")
      lines.push("")
    }

    if (config.styling.includes("styled-components")) {
      lines.push('echo "🎨 Installing Styled Components..."')
      lines.push("npm install styled-components")
      if (isTs) lines.push("npm install -D @types/styled-components")
      lines.push("")
    }

    if (config.styling.includes("emotion")) {
      lines.push('echo "🎨 Installing Emotion..."')
      lines.push("npm install @emotion/react @emotion/styled")
      lines.push("")
    }

    if (config.styling.includes("vanilla-extract")) {
      lines.push('echo "🎨 Installing Vanilla Extract..."')
      lines.push("npm install @vanilla-extract/css @vanilla-extract/vite-plugin")
      lines.push("")
    }

    // UI Libraries
    if (config.uiLibrary.includes("shadcn")) {
      lines.push('echo "🧩 Installing shadcn/ui..."')
      lines.push("npx shadcn@latest init -y")
      lines.push("npx shadcn@latest add button card input label")
      lines.push("")
    }

    if (config.uiLibrary.includes("antd")) {
      lines.push('echo "🧩 Installing Ant Design..."')
      lines.push("npm install antd @ant-design/icons")
      lines.push("")
    }

    if (config.uiLibrary.includes("mui")) {
      lines.push('echo "🧩 Installing Material UI..."')
      lines.push("npm install @mui/material @emotion/react @emotion/styled @mui/icons-material")
      lines.push("")
    }

    if (config.uiLibrary.includes("chakra")) {
      lines.push('echo "🧩 Installing Chakra UI..."')
      lines.push("npm install @chakra-ui/react @emotion/react @emotion/styled framer-motion")
      lines.push("")
    }

    if (config.uiLibrary.includes("radix")) {
      lines.push('echo "🧩 Installing Radix UI..."')
      lines.push("npm install @radix-ui/react-dialog @radix-ui/react-dropdown-menu @radix-ui/react-slot")
      lines.push("")
    }

    if (config.uiLibrary.includes("headless")) {
      lines.push('echo "🧩 Installing Headless UI..."')
      lines.push("npm install @headlessui/react")
      lines.push("")
    }

    if (config.uiLibrary.includes("daisyui")) {
      lines.push('echo "🧩 Installing DaisyUI..."')
      lines.push("npm install -D daisyui@latest")
      lines.push("")
    }

    if (config.uiLibrary.includes("nextui")) {
      lines.push('echo "🧩 Installing NextUI..."')
      lines.push("npm install @nextui-org/react framer-motion")
      lines.push("")
    }

    if (config.uiLibrary.includes("mantine")) {
      lines.push('echo "🧩 Installing Mantine..."')
      lines.push("npm install @mantine/core @mantine/hooks @mantine/form")
      lines.push("")
    }

    if (config.uiLibrary.includes("arco")) {
      lines.push('echo "🧩 Installing Arco Design..."')
      lines.push("npm install @arco-design/web-react")
      lines.push("")
    }

    if (config.uiLibrary.includes("primereact")) {
      lines.push('echo "🧩 Installing PrimeReact..."')
      lines.push("npm install primereact primeicons")
      lines.push("")
    }

    if (config.uiLibrary.includes("flowbite")) {
      lines.push('echo "🧩 Installing Flowbite..."')
      lines.push("npm install flowbite flowbite-react")
      lines.push("")
    }

    if (config.stateManagement.includes("zustand")) {
      lines.push('echo "📦 Installing Zustand..."')
      lines.push("npm install zustand")
      lines.push("")
    }

    if (config.stateManagement.includes("redux")) {
      lines.push('echo "📦 Installing Redux Toolkit..."')
      lines.push("npm install @reduxjs/toolkit react-redux")
      lines.push("")
    }

    if (config.stateManagement.includes("jotai")) {
      lines.push('echo "📦 Installing Jotai..."')
      lines.push("npm install jotai")
      lines.push("")
    }

    if (config.stateManagement.includes("recoil")) {
      lines.push('echo "📦 Installing Recoil..."')
      lines.push("npm install recoil")
      lines.push("")
    }

    if (config.stateManagement.includes("tanstack-query")) {
      lines.push('echo "📦 Installing TanStack Query..."')
      lines.push("npm install @tanstack/react-query @tanstack/react-query-devtools")
      lines.push("")
    }

    if (config.stateManagement.includes("apollo")) {
      lines.push('echo "📦 Installing Apollo Client..."')
      lines.push("npm install @apollo/client graphql")
      lines.push("")
    }

    if (config.stateManagement.includes("swr")) {
      lines.push('echo "📦 Installing SWR..."')
      lines.push("npm install swr")
      lines.push("")
    }

    if (config.stateManagement.includes("mobx")) {
      lines.push('echo "📦 Installing MobX..."')
      lines.push("npm install mobx mobx-react-lite")
      lines.push("")
    }

    if (config.animation.includes("framer-motion")) {
      lines.push('echo "✨ Installing Framer Motion..."')
      lines.push("npm install framer-motion")
      lines.push("")
    }

    if (config.animation.includes("gsap")) {
      lines.push('echo "✨ Installing GSAP..."')
      lines.push("npm install gsap")
      lines.push("")
    }

    if (config.animation.includes("react-spring")) {
      lines.push('echo "✨ Installing React Spring..."')
      lines.push("npm install @react-spring/web")
      lines.push("")
    }

    if (config.animation.includes("auto-animate")) {
      lines.push('echo "✨ Installing AutoAnimate..."')
      lines.push("npm install @formkit/auto-animate")
      lines.push("")
    }

    if (config.animation.includes("lottie")) {
      lines.push('echo "✨ Installing Lottie..."')
      lines.push("npm install lottie-react")
      lines.push("")
    }

    if (config.dataViz.includes("recharts")) {
      lines.push('echo "📊 Installing Recharts..."')
      lines.push("npm install recharts")
      lines.push("")
    }

    if (config.dataViz.includes("chartjs")) {
      lines.push('echo "📊 Installing Chart.js..."')
      lines.push("npm install chart.js react-chartjs-2")
      lines.push("")
    }

    if (config.dataViz.includes("d3")) {
      lines.push('echo "📊 Installing D3.js..."')
      lines.push("npm install d3")
      if (isTs) lines.push("npm install -D @types/d3")
      lines.push("")
    }

    if (config.dataViz.includes("echarts")) {
      lines.push('echo "📊 Installing ECharts..."')
      lines.push("npm install echarts echarts-for-react")
      lines.push("")
    }

    if (config.dataViz.includes("visx")) {
      lines.push('echo "📊 Installing visx..."')
      lines.push("npm install @visx/visx")
      lines.push("")
    }

    if (config.dataViz.includes("nivo")) {
      lines.push('echo "📊 Installing Nivo..."')
      lines.push("npm install @nivo/core @nivo/bar @nivo/line @nivo/pie")
      lines.push("")
    }

    // BaaS / Services
    if (config.baas.includes("firebase")) {
      lines.push('echo "🔥 Installing Firebase..."')
      lines.push("npm install firebase")
      lines.push("")
    }

    if (config.baas.includes("supabase")) {
      lines.push('echo "⚡ Installing Supabase..."')
      lines.push("npm install @supabase/supabase-js @supabase/ssr")
      lines.push("")
    }

    if (config.baas.includes("appwrite")) {
      lines.push('echo "📝 Installing Appwrite..."')
      lines.push("npm install appwrite")
      lines.push("")
    }

    if (config.baas.includes("convex")) {
      lines.push('echo "🔄 Installing Convex..."')
      lines.push("npm install convex")
      lines.push("")
    }

    if (config.baas.includes("pocketbase")) {
      lines.push('echo "📦 Installing PocketBase SDK..."')
      lines.push("npm install pocketbase")
      lines.push("")
    }

    if (config.baas.includes("clerk")) {
      lines.push('echo "🔐 Installing Clerk..."')
      lines.push("npm install @clerk/nextjs")
      lines.push("")
    }

    if (config.baas.includes("auth0")) {
      lines.push('echo "🔐 Installing Auth0..."')
      lines.push("npm install @auth0/auth0-react")
      lines.push("")
    }

    if (config.baas.includes("nextauth")) {
      lines.push('echo "🔐 Installing NextAuth.js..."')
      lines.push("npm install next-auth")
      lines.push("")
    }

    if (config.baas.includes("lucia")) {
      lines.push('echo "🔐 Installing Lucia..."')
      lines.push("npm install lucia @lucia-auth/adapter-prisma")
      lines.push("")
    }

    if (config.baas.includes("stripe")) {
      lines.push('echo "💳 Installing Stripe..."')
      lines.push("npm install @stripe/stripe-js stripe")
      lines.push("")
    }

    if (config.baas.includes("lemonsqueezy")) {
      lines.push('echo "💳 Installing Lemon Squeezy..."')
      lines.push("npm install @lemonsqueezy/lemonsqueezy.js")
      lines.push("")
    }

    if (config.baas.includes("resend")) {
      lines.push('echo "📧 Installing Resend..."')
      lines.push("npm install resend")
      lines.push("")
    }

    if (config.baas.includes("uploadthing")) {
      lines.push('echo "📤 Installing UploadThing..."')
      lines.push("npm install uploadthing @uploadthing/react")
      lines.push("")
    }

    if (config.baas.includes("neon")) {
      lines.push('echo "🐘 Installing Neon..."')
      lines.push("npm install @neondatabase/serverless")
      lines.push("")
    }

    if (config.baas.includes("planetscale")) {
      lines.push('echo "🐘 Installing PlanetScale..."')
      lines.push("npm install @planetscale/database")
      lines.push("")
    }

    if (config.baas.includes("upstash")) {
      lines.push('echo "🔴 Installing Upstash..."')
      lines.push("npm install @upstash/redis @upstash/ratelimit")
      lines.push("")
    }

    // Testing
    if (config.testing.includes("jest")) {
      lines.push('echo "🧪 Installing Jest..."')
      lines.push("npm install -D jest @types/jest")
      lines.push("")
    }

    if (config.testing.includes("vitest")) {
      lines.push('echo "🧪 Installing Vitest..."')
      lines.push("npm install -D vitest @vitest/ui")
      lines.push("")
    }

    if (config.testing.includes("cypress")) {
      lines.push('echo "🧪 Installing Cypress..."')
      lines.push("npm install -D cypress")
      lines.push("")
    }

    if (config.testing.includes("playwright")) {
      lines.push('echo "🧪 Installing Playwright..."')
      lines.push("npm install -D @playwright/test")
      lines.push("npx playwright install")
      lines.push("")
    }

    if (config.testing.includes("rtl")) {
      lines.push('echo "🧪 Installing React Testing Library..."')
      lines.push("npm install -D @testing-library/react @testing-library/jest-dom @testing-library/user-event")
      lines.push("")
    }

    if (config.testing.includes("msw")) {
      lines.push('echo "🧪 Installing MSW..."')
      lines.push("npm install -D msw")
      lines.push("")
    }

    if (config.testing.includes("storybook")) {
      lines.push('echo "📚 Installing Storybook..."')
      lines.push("npx storybook@latest init")
      lines.push("")
    }

    // Linting
    if (config.linting.includes("eslint") && !["next", "nuxt"].includes(config.frontend)) {
      lines.push('echo "✨ Installing ESLint..."')
      lines.push("npm install -D eslint")
      lines.push("")
    }

    if (config.linting.includes("prettier")) {
      lines.push('echo "✨ Installing Prettier..."')
      lines.push("npm install -D prettier")
      lines.push("")
    }

    if (config.linting.includes("husky")) {
      lines.push('echo "🐶 Installing Husky..."')
      lines.push("npm install -D husky")
      lines.push("npx husky init")
      lines.push("")
    }

    if (config.linting.includes("lint-staged")) {
      lines.push('echo "📋 Installing lint-staged..."')
      lines.push("npm install -D lint-staged")
      lines.push("")
    }

    if (config.linting.includes("commitlint")) {
      lines.push('echo "📝 Installing Commitlint..."')
      lines.push("npm install -D @commitlint/cli @commitlint/config-conventional")
      lines.push("")
    }

    if (config.linting.includes("biome")) {
      lines.push('echo "⚡ Installing Biome..."')
      lines.push("npm install -D @biomejs/biome")
      lines.push("")
    }

    if (config.tooling.includes("docker")) {
      lines.push('echo "🐳 Creating Docker files..."')
      lines.push("touch Dockerfile docker-compose.yml .dockerignore")
      lines.push("")
    }

    if (config.tooling.includes("github-actions")) {
      lines.push('echo "🔧 Creating GitHub Actions..."')
      lines.push("mkdir -p .github/workflows")
      lines.push("touch .github/workflows/ci.yml")
      lines.push("")
    }

    // Custom folders
    if (folders.length > 0) {
      lines.push("# ========================================")
      lines.push("# Custom Folder Structure")
      lines.push("# ========================================")
      lines.push('echo "📁 Creating custom folder structure..."')
      lines.push("")

      const createFolderCommands = (nodes: FolderNode[], basePath: string) => {
        for (const node of nodes) {
          const path = `${basePath}/${node.name}`
          if (node.type === "folder") {
            lines.push(`mkdir -p ${path}`)
            if (node.children && node.children.length > 0) {
              createFolderCommands(node.children, path)
            }
          } else {
            lines.push(`touch ${path}`)
          }
        }
      }

      createFolderCommands(folders, "src")
      lines.push("")
    }

    lines.push("cd ..")
    lines.push("")
  }

  // Backend setup
  if (config.backend !== "none") {
    lines.push("# ========================================")
    lines.push("# Backend Setup")
    lines.push("# ========================================")
    lines.push('echo "🖥️ Setting up backend..."')
    lines.push("")
    lines.push("mkdir -p server")
    lines.push("cd server")
    lines.push("")

    switch (config.backend) {
      case "express":
      case "fastify":
      case "hono":
        lines.push("npm init -y")
        if (config.backend === "express") {
          lines.push("npm install express cors dotenv helmet morgan")
          if (config.variant === "ts") {
            lines.push("npm install -D typescript @types/express @types/cors @types/node ts-node nodemon")
          }
        } else if (config.backend === "fastify") {
          lines.push("npm install fastify @fastify/cors dotenv")
          if (config.variant === "ts") {
            lines.push("npm install -D typescript @types/node ts-node nodemon")
          }
        } else if (config.backend === "hono") {
          lines.push("npm install hono")
          if (config.variant === "ts") {
            lines.push("npm install -D typescript @types/node tsx")
          }
        }
        break
      case "nest":
        lines.push("cd ..")
        lines.push("rm -rf server")
        lines.push("npx @nestjs/cli new server")
        lines.push("cd server")
        break
      case "bun":
        lines.push("bun init")
        lines.push("bun add hono")
        break
      case "deno":
        lines.push("deno init")
        break
      case "flask":
        lines.push("python -m venv venv")
        lines.push("source venv/bin/activate")
        lines.push("pip install flask flask-cors python-dotenv")
        lines.push('echo "flask\\nflask-cors\\npython-dotenv" > requirements.txt')
        lines.push("mkdir app && touch app/__init__.py app/routes.py")
        break
      case "fastapi":
        lines.push("python -m venv venv")
        lines.push("source venv/bin/activate")
        lines.push("pip install fastapi uvicorn python-dotenv pydantic sqlalchemy")
        lines.push('echo "fastapi\\nuvicorn\\npython-dotenv\\npydantic\\nsqlalchemy" > requirements.txt')
        lines.push("mkdir app && touch app/__init__.py app/main.py app/models.py app/schemas.py")
        break
      case "django":
        lines.push("python -m venv venv")
        lines.push("source venv/bin/activate")
        lines.push("pip install django djangorestframework django-cors-headers python-dotenv")
        lines.push("django-admin startproject backend .")
        lines.push("python manage.py startapp api")
        break
      case "spring":
        lines.push('echo "📋 Spring Boot Setup Instructions:"')
        lines.push('echo ""')
        lines.push('echo "1. Visit: https://start.spring.io"')
        lines.push('echo "2. Select: Maven/Gradle, Java 17+"')
        lines.push('echo "3. Add: Spring Web, Spring Data JPA, PostgreSQL Driver, Lombok"')
        lines.push('echo "4. Generate and extract to this directory"')
        lines.push('echo ""')
        lines.push('echo "Or use Spring CLI: spring init --dependencies=web,data-jpa,postgresql,lombok ."')
        break
      case "quarkus":
        lines.push('echo "📋 Quarkus Setup:"')
        lines.push("mvn io.quarkus.platform:quarkus-maven-plugin:3.0.0.Final:create")
        break
      case "gin":
        lines.push("go mod init server")
        lines.push("go get -u github.com/gin-gonic/gin")
        lines.push("touch main.go")
        break
      case "fiber":
        lines.push("go mod init server")
        lines.push("go get -u github.com/gofiber/fiber/v2")
        lines.push("touch main.go")
        break
    }
    lines.push("")

    // Database setup
    if (config.database !== "none") {
      lines.push("# Database dependencies")
      switch (config.database) {
        case "prisma-postgres":
        case "prisma-mysql":
          lines.push("npm install prisma @prisma/client")
          lines.push("npx prisma init")
          break
        case "drizzle":
          lines.push("npm install drizzle-orm postgres")
          lines.push("npm install -D drizzle-kit")
          break
        case "mongodb":
        case "mongoose":
          lines.push("npm install mongoose")
          break
        case "typeorm":
          lines.push("npm install typeorm reflect-metadata pg")
          break
        case "sequelize":
          lines.push("npm install sequelize pg pg-hstore")
          break
        case "kysely":
          lines.push("npm install kysely pg")
          break
        case "sqlite":
          lines.push("npm install better-sqlite3")
          if (config.variant === "ts") lines.push("npm install -D @types/better-sqlite3")
          break
        case "redis":
          lines.push("npm install redis")
          break
      }
      lines.push("")
    }

    lines.push("cd ..")
    lines.push("")
  }

  if (config.tooling.includes("turborepo") || config.tooling.includes("nx")) {
    lines.push("# ========================================")
    lines.push("# Monorepo Setup")
    lines.push("# ========================================")
    if (config.tooling.includes("turborepo")) {
      lines.push('echo "📦 Initializing Turborepo..."')
      lines.push("npm install turbo --save-dev")
    }
    if (config.tooling.includes("nx")) {
      lines.push('echo "📦 Initializing Nx..."')
      lines.push("npx nx@latest init")
    }
    lines.push("")
  }

  // Git init
  lines.push("# ========================================")
  lines.push("# Git Initialization")
  lines.push("# ========================================")
  lines.push('echo "🔧 Initializing git repository..."')
  lines.push("git init")
  lines.push("")

  // Final message
  lines.push('echo ""')
  lines.push('echo "✅ Project setup complete!"')
  lines.push('echo ""')
  lines.push(`echo "📁 Project created at: ${config.projectName}"`)
  lines.push('echo ""')
  lines.push('echo "To get started:"')
  lines.push(`echo "  cd ${config.projectName}"`)
  if (config.frontend !== "none") {
    lines.push('echo "  cd client && npm run dev"')
  }
  if (
    config.backend !== "none" &&
    !["flask", "fastapi", "django", "spring", "quarkus", "gin", "fiber"].includes(config.backend)
  ) {
    lines.push('echo "  cd server && npm run dev"')
  }
  if (["flask", "fastapi", "django"].includes(config.backend)) {
    lines.push('echo "  cd server && source venv/bin/activate"')
    if (config.backend === "fastapi") {
      lines.push('echo "  uvicorn app.main:app --reload"')
    } else if (config.backend === "django") {
      lines.push('echo "  python manage.py runserver"')
    } else {
      lines.push('echo "  flask run --debug"')
    }
  }
  lines.push('echo ""')
  lines.push('echo "Happy coding! 🎉"')

  return lines.join("\n")
}
